### PR TITLE
Extend filename with hour/minute/seconds

### PR DESCRIPTION
**Pull request by ronaldme**
With option to override the date time formatting using the CommandArgs

### CODE REVIEW

**Comment by ronaldme** [comment]
One mistake I just found out while testing, guess I have to ammend it to this commit.

string dateTime = DateTime.Now.ToString(dateTimeFormat ?? "yyyyMMdd_HH-mm-ss");

**Comment by ronaldme** [comment]
Just did a force-push, should be fixed now.

**Comment by chrismckelt** [comment]
@ronaldme sorry I have been on holiday & just noticed this - thanks for your contribution 👍

**Comment by chrismckelt** [comment]
Released via Nuget in version 1.0.5

**Pull request merged**
